package scan

import "testing"

func TestUnpinnedRuntimeToolDetection(t *testing.T) {
	cases := []struct {
		line string
		want bool
	}{
		{line: "npx tool", want: true},
		{line: "npx --yes tool@latest", want: true},
		{line: "npx tool@next", want: true},
		{line: "npx tool@^1.2.3", want: true},
		{line: "npx tool@1.2.3", want: false},
		{line: "uvx @scope/tool", want: true},
		{line: "uvx @scope/tool@next", want: true},
		{line: "uvx @scope/tool@0.9.1", want: false},
		{line: "bunx @scope/tool", want: true},
		{line: "bunx @scope/tool@beta", want: true},
		{line: "bunx @scope/tool@1.2.3", want: false},
		{line: "pnpm dlx @scope/tool", want: true},
		{line: "pnpm 'dlx' @scope/tool", want: true},
		{line: "pnpm dlx @scope/tool@canary", want: true},
		{line: "pnpm dlx @scope/tool@1.2.3", want: false},
		{line: "pnpm dlx --package @scope/tool -- tool", want: true},
		{line: "pnpm dlx --package @scope/tool@1.2.3 -- tool", want: false},
		{line: "pnpm dlx --package @scope/tool@1.2.3 -- @scope/other", want: true},
		{line: "pnpm dlx -c \"echo hi\"", want: false},
		{line: "pnpm --color=always dlx @scope/tool", want: true},
		{line: "pnpm --color=always dlx", want: false},
		{line: "pnpm install @scope/tool", want: false},
		{line: "yarn dlx @scope/tool", want: true},
		{line: "yarn \"DLX\" @scope/tool", want: true},
		{line: "yarn dlx @scope/tool@1.2.3", want: false},
		{line: "yarn dlx --package @scope/tool -- tool", want: true},
		{line: "yarn dlx --package @scope/tool@1.2.3 -- tool", want: false},
		{line: "yarn dlx --package @scope/tool@1.2.3 -- @scope/other", want: true},
		{line: "yarn dlx -c \"echo hi\"", want: false},
		{line: "npm exec @scope/tool", want: true},
		{line: "npm 'exec' @scope/tool", want: true},
		{line: "npm exec @scope/tool@1.2.3", want: false},
		{line: "npm exec -- @scope/tool", want: true},
		{line: "npm exec -- @scope/tool@1.2.3", want: false},
		{line: "npm exec --package @scope/tool -- tool", want: true},
		{line: "npm exec --package=@scope/tool -- tool", want: true},
		{line: "npm exec -p @scope/tool -- tool", want: true},
		{line: "npm exec -p@scope/tool -- tool", want: true},
		{line: "npm exec '--package=@scope/tool' -- tool", want: true},
		{line: "npm exec --package @scope/tool@1.2.3 -- tool", want: false},
		{line: "npm exec --package=@scope/tool@1.2.3 -- tool", want: false},
		{line: "npm exec -p @scope/tool@1.2.3 -- tool", want: false},
		{line: "npm exec -p@scope/tool@1.2.3 -- tool", want: false},
		{line: "npm exec '--package=@scope/tool@1.2.3' -- tool", want: false},
		{line: "npm exec --package @scope/tool@1.2.3 -- @scope/other", want: true},
		{line: "npm exec --package @scope/tool@1.2.3 -- @scope/other@2.0.0", want: false},
		{line: "npm exec --call \"echo hi\"", want: false},
		{line: "npm exec -c \"echo hi\"", want: false},
		{line: "npm --yes exec @scope/tool", want: true},
		{line: "npm exec", want: false},
		{line: "npm exec --", want: false},
		{line: "corepack pnpm dlx @scope/tool", want: true},
		{line: "echo;corepack pnpm dlx @scope/tool", want: true},
		{line: "echo;!corepack pnpm dlx @scope/tool", want: true},
		{line: "corepack pnpm;dlx @scope/tool", want: true},
		{line: "corepack pnpm;dlx @scope/tool@1.2.3", want: false},
		{line: "$(corepack pnpm dlx @scope/tool)", want: true},
		{line: "echo;$(corepack pnpm dlx @scope/tool)", want: true},
		{line: "corepack pnpm@latest dlx @scope/tool", want: true},
		{line: "corepack pnpm@9.0.0 dlx @scope/tool", want: true},
		{line: "corepack yarn dlx @scope/tool", want: true},
		{line: "corepack yarn@stable dlx @scope/tool", want: true},
		{line: "corepack npm exec @scope/tool", want: true},
		{line: "corepack npm@10 exec @scope/tool", want: true},
		{line: "corepack npm;exec @scope/tool", want: true},
		{line: "corepack npm;exec @scope/tool@1.2.3", want: false},
		{line: "corepack --install-directory ~/.local/bin pnpm dlx @scope/tool", want: true},
		{line: "corepack pnpm dlx @scope/tool@1.2.3", want: false},
		{line: "$(corepack pnpm dlx @scope/tool@1.2.3)", want: false},
		{line: "corepack pnpm dlx --package @scope/tool@1.2.3 -- @scope/other", want: true},
		{line: "corepack pnpm@9.0.0 dlx @scope/tool@1.2.3", want: false},
		{line: "corepack yarn dlx @scope/tool@1.2.3", want: false},
		{line: "corepack npm exec @scope/tool@1.2.3", want: false},
		{line: "corepack npm exec --package @scope/tool@1.2.3 -- tool", want: false},
		{line: "corepack npm exec -- @scope/tool@1.2.3", want: false},
		{line: "corepack npm exec --", want: false},
		{line: "npx -p @scope/tool -c tool", want: true},
		{line: "npx -p@scope/tool -c tool", want: true},
		{line: "npx '-p@scope/tool' -c tool", want: true},
		{line: "npx --package=@scope/tool -c tool", want: true},
		{line: "npx -p @scope/tool@1.2.3 -c tool", want: false},
		{line: "npx -p@scope/tool@1.2.3 -c tool", want: false},
		{line: "npx '-p@scope/tool@1.2.3' -c tool", want: false},
		{line: "npx --package=@scope/tool@1.2.3 -c tool", want: false},
		{line: "npx -c \"echo hi\"", want: false},
		{line: "npx -cecho hi", want: false},
		{line: "npx --yes", want: false},
		{line: "echo prep &&npx tool", want: true},
		{line: "echo prep $(npx tool)", want: true},
		{line: "echo prep !npx tool", want: true},
		{line: "echo;npx tool", want: true},
		{line: "echo;!npx tool", want: true},
		{line: "echo;npx tool@1.2.3", want: false},
		{line: "echo prep &&npx tool@1.2.3", want: false},
		{line: "echo prep ||npx tool", want: true},
		{line: "deno run -A npm:create-next-app@latest", want: true},
		{line: "$(deno run -A npm:create-next-app@latest)", want: true},
		{line: "!deno run -A npm:create-next-app@latest", want: true},
		{line: "echo;deno run -A npm:create-next-app@latest", want: true},
		{line: "echo;!deno run -A npm:create-next-app@latest", want: true},
		{line: "echo;deno run -A npm:create-next-app@15.4.1", want: false},
		{line: "echo;!deno run -A npm:create-next-app@15.4.1", want: false},
		{line: "&&deno run -A npm:create-next-app@latest", want: true},
		{line: "\"deno\" run -A npm:create-next-app@latest", want: true},
		{line: "deno \"run\" -A npm:create-next-app@latest", want: true},
		{line: "\\\"deno\\\" \\\"run\\\" -A npm:create-next-app@latest", want: true},
		{line: "echo prep &&deno run -A npm:create-next-app@latest", want: true},
		{line: "echo prep &&deno run -A npm:create-next-app@15.4.1", want: false},
		{line: "echo prep && deno run -A npm:create-next-app@latest", want: true},
		{line: "echo prep && deno run -A npm:create-next-app@15.4.1", want: false},
		{line: "echo prep && deno run https://deno.land/x/install.ts", want: true},
		{line: "deno run -A npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-read npm:cowsay@1.5.0", want: false},
		{line: "deno run --allow-read npm:cowsay", want: true},
		{line: "deno run --allow-read -- npm:create-next-app@latest", want: true},
		{line: "deno run --reload npm:create-next-app@latest", want: true},
		{line: "deno run -r npm:create-next-app@latest", want: true},
		{line: "deno run --reload npm:chalk@5 npm:create-next-app@latest", want: true},
		{line: "deno run -r npm:chalk@5 npm:create-next-app@latest", want: true},
		{line: "deno run --reload jsr:@std/http@1.0.0 npm:create-next-app@latest", want: true},
		{line: "deno run --reload npm:chalk@5 main.ts", want: false},
		{line: "deno run --vendor npm:create-next-app@latest", want: true},
		{line: "deno run --vendor true npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-dir npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-dir auto npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-linker isolated npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-linker isolated npm:create-next-app@15.4.1", want: false},
		{line: "deno run --minimum-dependency-age 0 npm:create-next-app@latest", want: true},
		{line: "deno run --minimum-dependency-age 0 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --lock npm:create-next-app@latest", want: true},
		{line: "deno run --lock npm:create-next-app@15.4.1", want: false},
		{line: "deno run --lock deno.lock npm:create-next-app@latest", want: true},
		{line: "deno run --lock deno.lock npm:create-next-app@15.4.1", want: false},
		{line: "deno run --cpu-prof-dir profiles npm:create-next-app@latest", want: true},
		{line: "deno run --cpu-prof-dir profiles npm:create-next-app@15.4.1", want: false},
		{line: "deno run --cpu-prof-interval 1000 npm:create-next-app@latest", want: true},
		{line: "deno run --cpu-prof-interval 1000 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --cpu-prof-name cpu.cpuprofile npm:create-next-app@latest", want: true},
		{line: "deno run --cpu-prof-name cpu.cpuprofile npm:create-next-app@15.4.1", want: false},
		{line: "deno run --tunnel preview npm:create-next-app@latest", want: true},
		{line: "deno run --tunnel preview npm:create-next-app@15.4.1", want: false},
		{line: "deno run -t preview npm:create-next-app@latest", want: true},
		{line: "deno run -t preview npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-scripts sqlite3 npm:create-next-app@latest", want: true},
		{line: "deno run --allow-scripts sqlite3 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-scripts sqlite3 main.ts", want: false},
		{line: "deno run --allow-scripts=npm:sqlite3 npm:create-next-app@latest", want: true},
		{line: "deno run --allow-scripts=npm:sqlite3 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-import deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-import deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run -I deno.land npm:create-next-app@latest", want: true},
		{line: "deno run -I deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-import=deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-import=deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-read=. npm:create-next-app@latest", want: true},
		{line: "deno run --allow-read=. npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-read . npm:create-next-app@latest", want: true},
		{line: "deno run --allow-read . npm:create-next-app@15.4.1", want: false},
		{line: "deno run -R . npm:create-next-app@latest", want: true},
		{line: "deno run -R . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-net=deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-net=deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-net deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-net deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run -N deno.land npm:create-next-app@latest", want: true},
		{line: "deno run -N deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-env=PATH npm:create-next-app@latest", want: true},
		{line: "deno run --allow-env=PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-env PATH npm:create-next-app@latest", want: true},
		{line: "deno run --allow-env PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run -E PATH npm:create-next-app@latest", want: true},
		{line: "deno run -E PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-write=. npm:create-next-app@latest", want: true},
		{line: "deno run --allow-write=. npm:create-next-app@15.4.1", want: false},
		{line: "deno run -W . npm:create-next-app@latest", want: true},
		{line: "deno run -W . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-run=deno,npm npm:create-next-app@latest", want: true},
		{line: "deno run --allow-run deno npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-ffi=./native.so npm:create-next-app@latest", want: true},
		{line: "deno run --allow-ffi ./native.so npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-sys=hostname npm:create-next-app@latest", want: true},
		{line: "deno run --allow-sys=hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-sys hostname npm:create-next-app@latest", want: true},
		{line: "deno run --allow-sys hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run -S hostname npm:create-next-app@latest", want: true},
		{line: "deno run -S hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-hrtime npm:create-next-app@latest", want: true},
		{line: "deno run --allow-hrtime npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-read . npm:create-next-app@latest", want: true},
		{line: "deno run --deny-read . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-write . npm:create-next-app@latest", want: true},
		{line: "deno run --deny-write . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-net deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --deny-net deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-env PATH npm:create-next-app@latest", want: true},
		{line: "deno run --deny-env PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-sys hostname npm:create-next-app@latest", want: true},
		{line: "deno run --deny-sys hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-run deno npm:create-next-app@latest", want: true},
		{line: "deno run --deny-run deno npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-ffi ./native.so npm:create-next-app@latest", want: true},
		{line: "deno run --deny-ffi ./native.so npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-import deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --deny-import deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --inspect 127.0.0.1:9229 npm:create-next-app@latest", want: true},
		{line: "deno run --inspect 127.0.0.1:9229 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --inspect-brk 127.0.0.1:9229 npm:create-next-app@latest", want: true},
		{line: "deno run --inspect-wait 127.0.0.1:9229 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --ext ts npm:create-next-app@latest", want: true},
		{line: "deno run --ext ts npm:create-next-app@15.4.1", want: false},
		{line: "deno run --env-file npm:create-next-app@latest", want: true},
		{line: "deno run --env-file npm:create-next-app@15.4.1", want: false},
		{line: "deno run --env-file .env npm:create-next-app@latest", want: true},
		{line: "deno run --env-file .env npm:create-next-app@15.4.1", want: false},
		{line: "deno run --require ./loader.cjs npm:create-next-app@latest", want: true},
		{line: "deno run --require ./loader.cjs npm:create-next-app@15.4.1", want: false},
		{line: "deno run --preload ./preload.ts npm:create-next-app@latest", want: true},
		{line: "deno run --preload ./preload.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno run --import ./preload.ts npm:create-next-app@latest", want: true},
		{line: "deno run --import ./preload.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno run --watch src npm:create-next-app@latest", want: true},
		{line: "deno run --watch src npm:create-next-app@15.4.1", want: false},
		{line: "deno run --watch-exclude dist npm:create-next-app@latest", want: true},
		{line: "deno run --watch-exclude dist npm:create-next-app@15.4.1", want: false},
		{line: "deno run --watch-hmr src npm:create-next-app@latest", want: true},
		{line: "deno run --watch-hmr src npm:create-next-app@15.4.1", want: false},
		{line: "deno run --conditions deno npm:create-next-app@latest", want: true},
		{line: "deno run --conditions deno npm:create-next-app@15.4.1", want: false},
		{line: "deno run --coverage coverage npm:create-next-app@latest", want: true},
		{line: "deno run --coverage coverage npm:create-next-app@15.4.1", want: false},
		{line: "deno run --coverage npm:create-next-app@latest", want: true},
		{line: "deno run --v8-flags --harmony npm:create-next-app@latest", want: true},
		{line: "deno run --v8-flags --harmony npm:create-next-app@15.4.1", want: false},
		{line: "deno run --no-check remote npm:create-next-app@latest", want: true},
		{line: "deno run --no-check remote npm:create-next-app@15.4.1", want: false},
		{line: "deno run --no-check npm:create-next-app@latest", want: true},
		{line: "deno run --check all npm:create-next-app@latest", want: true},
		{line: "deno run --check all npm:create-next-app@15.4.1", want: false},
		{line: "deno run --check npm:create-next-app@latest", want: true},
		{line: "deno run --frozen false npm:create-next-app@latest", want: true},
		{line: "deno run --frozen false npm:create-next-app@15.4.1", want: false},
		{line: "deno run --frozen npm:create-next-app@latest", want: true},
		{line: "deno run -L debug npm:create-next-app@latest", want: true},
		{line: "deno run -L debug npm:create-next-app@15.4.1", want: false},
		{line: "deno run --log-level debug npm:create-next-app@latest", want: true},
		{line: "deno run --log-level debug npm:create-next-app@15.4.1", want: false},
		{line: "deno run --unstable-kv npm:create-next-app@latest", want: true},
		{line: "deno run --unstable-kv npm:create-next-app@15.4.1", want: false},
		{line: "deno run --unstable-broadcast-channel npm:create-next-app@latest", want: true},
		{line: "deno run --unstable-broadcast-channel npm:create-next-app@15.4.1", want: false},
		{line: "deno run --strace-ops=open,read npm:create-next-app@latest", want: true},
		{line: "deno run --strace-ops open,read npm:create-next-app@15.4.1", want: false},
		{line: "deno run --strace-filter=pid=1 npm:create-next-app@latest", want: true},
		{line: "deno run --strace-filter pid=1 npm:create-next-app@15.4.1", want: false},
		{line: "DENO RUN -R . npm:create-next-app@latest", want: true},
		{line: "Deno Run -E PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno x npm:create-vite", want: true},
		{line: "deno x npm:create-vite@5.2.0", want: false},
		{line: "deno x -p npm:create-vite@5.2.0 create-vite", want: false},
		{line: "deno x -p npm:create-vite create-vite", want: true},
		{line: "deno x -pnpm:create-vite@5.2.0 create-vite", want: false},
		{line: "deno x -pnpm:create-vite@latest create-vite", want: true},
		{line: "deno x --package npm:create-vite@5.2.0 create-vite", want: false},
		{line: "deno x --package npm:create-vite create-vite", want: true},
		{line: "deno x --install-alias denox npm:create-vite", want: true},
		{line: "deno x --install-alias denox npm:create-vite@5.2.0", want: false},
		{line: "deno x --install-alias npm:create-vite@latest", want: true},
		{line: "deno x --install-alias", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 npm:other@latest", want: true},
		{line: "deno x --package npm:create-vite@5.2.0 npm:other@1.2.3", want: false},
		{line: "deno x --package npm:create-vite@5.2.0", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 --package npm:other@latest create-vite", want: true},
		{line: "deno x --package npm:create-vite@5.2.0 --package npm:other@1.2.3 create-vite", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 --package jsr:@std/http@1.0.0 create-vite", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 --package jsr:@std/http create-vite", want: true},
		{line: "deno create npm:vite", want: true},
		{line: "deno create npm:vite@6.0.0", want: false},
		{line: "deno create jsr:@fresh/init", want: true},
		{line: "deno create jsr:@fresh/init@2.3.3", want: false},
		{line: "deno create --npm create-vite", want: true},
		{line: "deno create --npm create-vite@6.0.0", want: false},
		{line: "deno create --jsr @fresh/init", want: true},
		{line: "deno create --jsr @fresh/init@2.3.3", want: false},
		{line: "deno create --npm create-vite -- my-app", want: true},
		{line: "deno create --npm -- my-app", want: false},
		{line: "deno init my-project", want: false},
		{line: "deno init --npm vite", want: true},
		{line: "deno init --npm vite@6.0.0", want: false},
		{line: "deno init --jsr @fresh/init", want: true},
		{line: "deno init --jsr @fresh/init@2.3.3", want: false},
		{line: "deno init npm:vite", want: true},
		{line: "deno init npm:vite@6.0.0", want: false},
		{line: "deno serve npm:create-next-app@latest", want: true},
		{line: "deno serve npm:create-next-app@15.4.1", want: false},
		{line: "deno serve jsr:@std/http", want: true},
		{line: "deno serve jsr:@std/http@1.0.0", want: false},
		{line: "deno serve --port 3000 npm:create-next-app@latest", want: true},
		{line: "deno serve --port 3000 npm:create-next-app@15.4.1", want: false},
		{line: "deno serve --host 127.0.0.1 npm:create-next-app@latest", want: true},
		{line: "deno serve --host 127.0.0.1 npm:create-next-app@15.4.1", want: false},
		{line: "deno install npm:create-next-app@latest", want: false},
		{line: "deno install npm:create-next-app@15.4.1", want: false},
		{line: "deno install jsr:@std/http", want: false},
		{line: "deno install jsr:@std/http@1.0.0", want: false},
		{line: "deno install --name cna npm:create-next-app@latest", want: false},
		{line: "deno install --name cna npm:create-next-app@15.4.1", want: false},
		{line: "deno install -n cna npm:create-next-app@latest", want: false},
		{line: "deno install -n cna npm:create-next-app@15.4.1", want: false},
		{line: "deno install --root /tmp/bin npm:create-next-app@latest", want: false},
		{line: "deno install --root /tmp/bin npm:create-next-app@15.4.1", want: false},
		{line: "deno install --entrypoint main.ts npm:create-next-app@latest", want: false},
		{line: "deno install --entrypoint main.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno install -e main.ts npm:create-next-app@latest", want: false},
		{line: "deno install -e main.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno install -g npm:create-next-app@latest", want: true},
		{line: "deno \"install\" -g npm:create-next-app@latest", want: true},
		{line: "deno install \"-g\" npm:create-next-app@latest", want: true},
		{line: "deno install -g npm:create-next-app@15.4.1", want: false},
		{line: "deno install -gNR npm:create-next-app@latest", want: true},
		{line: "deno install -gNR npm:create-next-app@15.4.1", want: false},
		{line: "deno install --global jsr:@std/http", want: true},
		{line: "deno install --global jsr:@std/http@1.0.0", want: false},
		{line: "deno install -g --name cna npm:create-next-app@latest", want: true},
		{line: "deno install -g --name cna npm:create-next-app@15.4.1", want: false},
		{line: "deno install --global=true npm:create-next-app@latest", want: true},
		{line: "deno install --global=true npm:create-next-app@15.4.1", want: false},
		{line: "deno install --global=false npm:create-next-app@latest", want: false},
		{line: "deno x jsr:@std/http/file-server", want: true},
		{line: "deno x jsr:@std/http@1.0.0/file-server", want: false},
		{line: "deno x -p jsr:@std/http@1.0.0 file-server", want: false},
		{line: "deno x -p jsr:@std/http file-server", want: true},
		{line: "deno x -pjsr:@std/http@1.0.0 file-server", want: false},
		{line: "deno x -pjsr:@std/http file-server", want: true},
		{line: "deno x --package jsr:@std/http@1.0.0 jsr:@std/fs", want: true},
		{line: "deno x --package jsr:@std/http@1.0.0 jsr:@std/fs@1.0.0", want: false},
		{line: "go run github.com/acme/x@latest", want: true},
		{line: "go \"run\" github.com/acme/x@latest", want: true},
		{line: "echo;go run github.com/acme/x@latest", want: true},
		{line: "echo;go \"run\" github.com/acme/x@latest", want: true},
		{line: "echo;!go run github.com/acme/x@latest", want: true},
		{line: "$(go run github.com/acme/x@latest)", want: true},
		{line: "$(go \"run\" github.com/acme/x@latest)", want: true},
		{line: "echo;$(go run github.com/acme/x@latest)", want: true},
		{line: "go run github.com/acme/x@main", want: true},
		{line: "go run github.com/acme/x@master", want: true},
		{line: "go run github.com/acme/x@v1", want: true},
		{line: "go run github.com/acme/x@v1.2.3", want: false},
		{line: "go run github.com/acme/x@v1.2.3-rc.1", want: false},
		{line: "go run github.com/acme/x@v1.2.3-20260523120000-abcdef123456", want: false},
		{line: "go run github.com/acme/x@abcdef123456", want: false},
		{line: "go run github.com/acme/x", want: true},
		{line: "go run golang.org/x/tools/cmd/stringer", want: true},
		{line: "go run -mod=mod github.com/acme/x@latest", want: true},
		{line: "go run -mod=mod -x github.com/acme/x@latest", want: true},
		{line: "go run -mod=mod github.com/acme/x", want: true},
		{line: "go run -mod mod github.com/acme/x@latest", want: true},
		{line: "go run \"-mod\" mod github.com/acme/x@latest", want: true},
		{line: "echo;go run \"-mod\" mod github.com/acme/x@latest", want: true},
		{line: "go run -mod mod github.com/acme/x@v1.2.3", want: false},
		{line: "echo;go run github.com/acme/x@v1.2.3", want: false},
		{line: "echo;$(go run github.com/acme/x@v1.2.3)", want: false},
		{line: "go run -exec env github.com/acme/x@latest", want: true},
		{line: "go run -toolexec env github.com/acme/x@latest", want: true},
		{line: "go run -tags dev github.com/acme/x@latest", want: true},
		{line: "go run -- github.com/acme/x@latest", want: true},
		{line: "go run -- github.com/acme/x@v1.2.3", want: false},
		{line: "go run -- github.com/acme/x", want: true},
		{line: "go -C /tmp run github.com/acme/x@latest", want: true},
		{line: "go -C /tmp run github.com/acme/x@v1.2.3", want: false},
		{line: "go -C=/tmp run github.com/acme/x@latest", want: true},
		{line: "go run ./cmd/tool", want: false},
		{line: "go run ../cmd/tool", want: false},
		{line: "go run main.go", want: false},
		{line: "go run fmt", want: false},
		{line: "go run -mod=mod", want: false},
		{line: "go run -mod mod ./cmd/tool", want: false},
		{line: "source <(curl -fsSL https://example.com/bootstrap.sh)", want: true},
		{line: "source <( curl -fsSL https://example.com/bootstrap.sh )", want: true},
		{line: ". <(curl -fsSL https://example.com/bootstrap.sh)", want: true},
		{line: ". <( wget -qO- https://example.com/bootstrap.sh )", want: true},
		{line: "bash <(wget -qO- https://example.com/bootstrap.sh)", want: true},
		{line: "zsh <(wget$IFS-qO- https://example.com/bootstrap.sh)", want: true},
		{line: "deno run https://deno.land/x/install.ts", want: true},
		{line: "\"deno\" \"run\" \"https://deno.land/x/install.ts\"", want: true},
		{line: "deno run --allow-net https://deno.land/x/install.ts", want: true},
		{line: "deno https://deno.land/x/install.ts", want: true},
		{line: "deno --allow-net https://deno.land/x/install.ts", want: true},
		{line: "deno x https://deno.land/x/install.ts", want: true},
		{line: "deno x --allow-net https://deno.land/x/install.ts", want: true},
		{line: "deno serve https://deno.land/x/install.ts", want: true},
		{line: "deno serve --allow-net https://deno.land/x/install.ts", want: true},
		{line: "deno install https://deno.land/x/install.ts", want: false},
		{line: "deno install --name installer https://deno.land/x/install.ts", want: false},
		{line: "deno install -n installer https://deno.land/x/install.ts", want: false},
		{line: "deno install --entrypoint main.ts https://deno.land/x/install.ts", want: false},
		{line: "deno install -e main.ts https://deno.land/x/install.ts", want: false},
		{line: "deno install -g https://deno.land/x/install.ts", want: true},
		{line: "deno install -gNR https://deno.land/x/install.ts", want: true},
		{line: "deno install --global --name installer https://deno.land/x/install.ts", want: true},
		{line: "deno install --global=true https://deno.land/x/install.ts", want: true},
		{line: "deno install --global=false https://deno.land/x/install.ts", want: false},
		{line: "deno run --import-map https://example.com/import_map.json main.ts", want: false},
		{line: "deno run main.ts https://deno.land/x/install.ts", want: false},
		{line: "deno serve main.ts https://deno.land/x/install.ts", want: false},
		{line: "deno install --name installer main.ts", want: false},
		{line: "deno install -n installer main.ts", want: false},
		{line: "source <(cat ./local.sh)", want: false},
		{line: ". <(cat ./local.sh)", want: false},
		{line: `"setup": "npx tool"`, want: true},
		{line: `"setup": "npx tool@1.2.3"`, want: false},
		{line: "NPX TOOL", want: true},
		{line: "echo safe", want: false},
	}
	for _, tc := range cases {
		if got := isUnpinnedRuntimeToolLine(tc.line); got != tc.want {
			t.Fatalf("isUnpinnedRuntimeToolLine(%q) = %v, want %v", tc.line, got, tc.want)
		}
	}
}
