package scan

import "testing"

func TestIsUnpinnedDenoNpmRuntimeLine(t *testing.T) {
	cases := []struct {
		line string
		want bool
	}{
		{line: "deno run -A npm:create-next-app@latest", want: true},
		{line: "!deno run -A npm:create-next-app@latest", want: true},
		{line: "\"deno\" run -A npm:create-next-app@latest", want: true},
		{line: "deno \"run\" -A npm:create-next-app@latest", want: true},
		{line: "\\\"deno\\\" \\\"run\\\" -A npm:create-next-app@latest", want: true},
		{line: "deno run -A npm:create-next-app@15.4.1", want: false},
		{line: "deno x npm:create-vite", want: true},
		{line: "deno x npm:create-vite@5.2.0", want: false},
		{line: "deno x -p npm:create-vite@5.2.0 create-vite", want: false},
		{line: "deno x -p npm:create-vite create-vite", want: true},
		{line: "deno x -pnpm:create-vite@5.2.0 create-vite", want: false},
		{line: "deno x -pnpm:create-vite@latest create-vite", want: true},
		{line: "deno x --install-alias denox npm:create-vite", want: true},
		{line: "deno x --install-alias denox npm:create-vite@5.2.0", want: false},
		{line: "deno x --install-alias npm:create-vite@latest", want: true},
		{line: "deno x --install-alias", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 npm:other@latest", want: true},
		{line: "deno x --package npm:create-vite@5.2.0 npm:other@1.2.3", want: false},
		{line: "deno x --package npm:create-vite@5.2.0", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 --package npm:other@latest create-vite", want: true},
		{line: "deno x --package npm:create-vite@5.2.0 --package npm:other@1.2.3 create-vite", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 --package jsr:@std/http@1.0.0 create-vite", want: false},
		{line: "deno x --package npm:create-vite@5.2.0 --package jsr:@std/http create-vite", want: true},
		{line: "deno create npm:vite", want: true},
		{line: "deno create npm:vite@6.0.0", want: false},
		{line: "deno create jsr:@fresh/init", want: true},
		{line: "deno create jsr:@fresh/init@2.3.3", want: false},
		{line: "deno create --npm create-vite", want: true},
		{line: "deno create --npm create-vite@6.0.0", want: false},
		{line: "deno create --jsr @fresh/init", want: true},
		{line: "deno create --jsr @fresh/init@2.3.3", want: false},
		{line: "deno create --npm create-vite -- my-app", want: true},
		{line: "deno create --npm -- my-app", want: false},
		{line: "deno init my-project", want: false},
		{line: "deno init --npm vite", want: true},
		{line: "deno init --npm vite@6.0.0", want: false},
		{line: "deno init --jsr @fresh/init", want: true},
		{line: "deno init --jsr @fresh/init@2.3.3", want: false},
		{line: "deno init npm:vite", want: true},
		{line: "deno init npm:vite@6.0.0", want: false},
		{line: "deno serve npm:create-next-app@latest", want: true},
		{line: "deno serve npm:create-next-app@15.4.1", want: false},
		{line: "deno serve jsr:@std/http", want: true},
		{line: "deno serve jsr:@std/http@1.0.0", want: false},
		{line: "deno serve --port 3000 npm:create-next-app@latest", want: true},
		{line: "deno serve --port 3000 npm:create-next-app@15.4.1", want: false},
		{line: "deno serve --host 127.0.0.1 npm:create-next-app@latest", want: true},
		{line: "deno serve --host 127.0.0.1 npm:create-next-app@15.4.1", want: false},
		{line: "deno install npm:create-next-app@latest", want: false},
		{line: "deno install npm:create-next-app@15.4.1", want: false},
		{line: "deno install jsr:@std/http", want: false},
		{line: "deno install jsr:@std/http@1.0.0", want: false},
		{line: "deno install --name cna npm:create-next-app@latest", want: false},
		{line: "deno install --name cna npm:create-next-app@15.4.1", want: false},
		{line: "deno install -n cna npm:create-next-app@latest", want: false},
		{line: "deno install -n cna npm:create-next-app@15.4.1", want: false},
		{line: "deno install --root /tmp/bin npm:create-next-app@latest", want: false},
		{line: "deno install --root /tmp/bin npm:create-next-app@15.4.1", want: false},
		{line: "deno install --entrypoint main.ts npm:create-next-app@latest", want: false},
		{line: "deno install --entrypoint main.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno install -e main.ts npm:create-next-app@latest", want: false},
		{line: "deno install -e main.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno install -g npm:create-next-app@latest", want: true},
		{line: "deno \"install\" -g npm:create-next-app@latest", want: true},
		{line: "deno install \"-g\" npm:create-next-app@latest", want: true},
		{line: "deno install -g npm:create-next-app@15.4.1", want: false},
		{line: "deno install -gNR npm:create-next-app@latest", want: true},
		{line: "deno install -gNR npm:create-next-app@15.4.1", want: false},
		{line: "deno install --global jsr:@std/http", want: true},
		{line: "deno install --global jsr:@std/http@1.0.0", want: false},
		{line: "deno install -g --name cna npm:create-next-app@latest", want: true},
		{line: "deno install -g --name cna npm:create-next-app@15.4.1", want: false},
		{line: "deno install --global=true npm:create-next-app@latest", want: true},
		{line: "deno install --global=true npm:create-next-app@15.4.1", want: false},
		{line: "deno install --global=false npm:create-next-app@latest", want: false},
		{line: "deno x jsr:@std/http/file-server", want: true},
		{line: "deno x jsr:@std/http@1.0.0/file-server", want: false},
		{line: "deno x -p jsr:@std/http@1.0.0 file-server", want: false},
		{line: "deno x -p jsr:@std/http file-server", want: true},
		{line: "deno x -pjsr:@std/http@1.0.0 file-server", want: false},
		{line: "deno x -pjsr:@std/http file-server", want: true},
		{line: "deno x --package jsr:@std/http@1.0.0 file-server", want: false},
		{line: "deno x --package jsr:@std/http file-server", want: true},
		{line: "deno x --package jsr:@std/http@1.0.0 jsr:@std/fs", want: true},
		{line: "deno x --package jsr:@std/http@1.0.0 jsr:@std/fs@1.0.0", want: false},
		{line: "deno run --reload npm:create-next-app@latest", want: true},
		{line: "deno run -r npm:create-next-app@latest", want: true},
		{line: "deno run --reload npm:chalk@5 npm:create-next-app@latest", want: true},
		{line: "deno run -r npm:chalk@5 npm:create-next-app@latest", want: true},
		{line: "deno run --reload jsr:@std/http@1.0.0 npm:create-next-app@latest", want: true},
		{line: "deno run --reload npm:chalk@5 main.ts", want: false},
		{line: "deno run --vendor npm:create-next-app@latest", want: true},
		{line: "deno run --vendor true npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-dir npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-dir auto npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-linker isolated npm:create-next-app@latest", want: true},
		{line: "deno run --node-modules-linker isolated npm:create-next-app@15.4.1", want: false},
		{line: "deno run --minimum-dependency-age 0 npm:create-next-app@latest", want: true},
		{line: "deno run --minimum-dependency-age 0 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --lock npm:create-next-app@latest", want: true},
		{line: "deno run --lock npm:create-next-app@15.4.1", want: false},
		{line: "deno run --lock deno.lock npm:create-next-app@latest", want: true},
		{line: "deno run --lock deno.lock npm:create-next-app@15.4.1", want: false},
		{line: "deno run --cpu-prof-dir profiles npm:create-next-app@latest", want: true},
		{line: "deno run --cpu-prof-dir profiles npm:create-next-app@15.4.1", want: false},
		{line: "deno run --cpu-prof-interval 1000 npm:create-next-app@latest", want: true},
		{line: "deno run --cpu-prof-interval 1000 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --cpu-prof-name cpu.cpuprofile npm:create-next-app@latest", want: true},
		{line: "deno run --cpu-prof-name cpu.cpuprofile npm:create-next-app@15.4.1", want: false},
		{line: "deno run --tunnel preview npm:create-next-app@latest", want: true},
		{line: "deno run --tunnel preview npm:create-next-app@15.4.1", want: false},
		{line: "deno run -t preview npm:create-next-app@latest", want: true},
		{line: "deno run -t preview npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-scripts sqlite3 npm:create-next-app@latest", want: true},
		{line: "deno run --allow-scripts sqlite3 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-scripts sqlite3 main.ts", want: false},
		{line: "deno run --allow-scripts=npm:sqlite3 npm:create-next-app@latest", want: true},
		{line: "deno run --allow-scripts=npm:sqlite3 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-import deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-import deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run -I deno.land npm:create-next-app@latest", want: true},
		{line: "deno run -I deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-import=deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-import=deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-read=. npm:create-next-app@latest", want: true},
		{line: "deno run --allow-read=. npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-read . npm:create-next-app@latest", want: true},
		{line: "deno run --allow-read . npm:create-next-app@15.4.1", want: false},
		{line: "deno run -R . npm:create-next-app@latest", want: true},
		{line: "deno run -R . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-net=deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-net=deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-net deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --allow-net deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run -N deno.land npm:create-next-app@latest", want: true},
		{line: "deno run -N deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-env=PATH npm:create-next-app@latest", want: true},
		{line: "deno run --allow-env=PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-env PATH npm:create-next-app@latest", want: true},
		{line: "deno run --allow-env PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run -E PATH npm:create-next-app@latest", want: true},
		{line: "deno run -E PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-write=. npm:create-next-app@latest", want: true},
		{line: "deno run --allow-write=. npm:create-next-app@15.4.1", want: false},
		{line: "deno run -W . npm:create-next-app@latest", want: true},
		{line: "deno run -W . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-run=deno,npm npm:create-next-app@latest", want: true},
		{line: "deno run --allow-run deno npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-ffi=./native.so npm:create-next-app@latest", want: true},
		{line: "deno run --allow-ffi ./native.so npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-sys=hostname npm:create-next-app@latest", want: true},
		{line: "deno run --allow-sys=hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-sys hostname npm:create-next-app@latest", want: true},
		{line: "deno run --allow-sys hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run -S hostname npm:create-next-app@latest", want: true},
		{line: "deno run -S hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run --allow-hrtime npm:create-next-app@latest", want: true},
		{line: "deno run --allow-hrtime npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-read . npm:create-next-app@latest", want: true},
		{line: "deno run --deny-read . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-write . npm:create-next-app@latest", want: true},
		{line: "deno run --deny-write . npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-net deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --deny-net deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-env PATH npm:create-next-app@latest", want: true},
		{line: "deno run --deny-env PATH npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-sys hostname npm:create-next-app@latest", want: true},
		{line: "deno run --deny-sys hostname npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-run deno npm:create-next-app@latest", want: true},
		{line: "deno run --deny-run deno npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-ffi ./native.so npm:create-next-app@latest", want: true},
		{line: "deno run --deny-ffi ./native.so npm:create-next-app@15.4.1", want: false},
		{line: "deno run --deny-import deno.land npm:create-next-app@latest", want: true},
		{line: "deno run --deny-import deno.land npm:create-next-app@15.4.1", want: false},
		{line: "deno run --inspect 127.0.0.1:9229 npm:create-next-app@latest", want: true},
		{line: "deno run --inspect 127.0.0.1:9229 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --inspect-brk 127.0.0.1:9229 npm:create-next-app@latest", want: true},
		{line: "deno run --inspect-wait 127.0.0.1:9229 npm:create-next-app@15.4.1", want: false},
		{line: "deno run --ext ts npm:create-next-app@latest", want: true},
		{line: "deno run --ext ts npm:create-next-app@15.4.1", want: false},
		{line: "deno run --env-file npm:create-next-app@latest", want: true},
		{line: "deno run --env-file npm:create-next-app@15.4.1", want: false},
		{line: "deno run --env-file .env npm:create-next-app@latest", want: true},
		{line: "deno run --env-file .env npm:create-next-app@15.4.1", want: false},
		{line: "deno run --require ./loader.cjs npm:create-next-app@latest", want: true},
		{line: "deno run --require ./loader.cjs npm:create-next-app@15.4.1", want: false},
		{line: "deno run --preload ./preload.ts npm:create-next-app@latest", want: true},
		{line: "deno run --preload ./preload.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno run --import ./preload.ts npm:create-next-app@latest", want: true},
		{line: "deno run --import ./preload.ts npm:create-next-app@15.4.1", want: false},
		{line: "deno run --watch src npm:create-next-app@latest", want: true},
		{line: "deno run --watch src npm:create-next-app@15.4.1", want: false},
		{line: "deno run --watch-exclude dist npm:create-next-app@latest", want: true},
		{line: "deno run --watch-exclude dist npm:create-next-app@15.4.1", want: false},
		{line: "deno run --watch-hmr src npm:create-next-app@latest", want: true},
		{line: "deno run --watch-hmr src npm:create-next-app@15.4.1", want: false},
		{line: "deno run --conditions deno npm:create-next-app@latest", want: true},
		{line: "deno run --conditions deno npm:create-next-app@15.4.1", want: false},
		{line: "deno run --coverage coverage npm:create-next-app@latest", want: true},
		{line: "deno run --coverage coverage npm:create-next-app@15.4.1", want: false},
		{line: "deno run --coverage npm:create-next-app@latest", want: true},
		{line: "deno run --v8-flags --harmony npm:create-next-app@latest", want: true},
		{line: "deno run --v8-flags --harmony npm:create-next-app@15.4.1", want: false},
		{line: "deno run --no-check remote npm:create-next-app@latest", want: true},
		{line: "deno run --no-check remote npm:create-next-app@15.4.1", want: false},
		{line: "deno run --no-check npm:create-next-app@latest", want: true},
		{line: "deno run --check all npm:create-next-app@latest", want: true},
		{line: "deno run --check all npm:create-next-app@15.4.1", want: false},
		{line: "deno run --check npm:create-next-app@latest", want: true},
		{line: "deno run --frozen false npm:create-next-app@latest", want: true},
		{line: "deno run --frozen false npm:create-next-app@15.4.1", want: false},
		{line: "deno run --frozen npm:create-next-app@latest", want: true},
		{line: "deno run -L debug npm:create-next-app@latest", want: true},
		{line: "deno run -L debug npm:create-next-app@15.4.1", want: false},
		{line: "deno run --log-level debug npm:create-next-app@latest", want: true},
		{line: "deno run --log-level debug npm:create-next-app@15.4.1", want: false},
		{line: "deno run --unstable-kv npm:create-next-app@latest", want: true},
		{line: "deno run --unstable-kv npm:create-next-app@15.4.1", want: false},
		{line: "deno run --unstable-broadcast-channel npm:create-next-app@latest", want: true},
		{line: "deno run --unstable-broadcast-channel npm:create-next-app@15.4.1", want: false},
		{line: "deno run --strace-ops=open,read npm:create-next-app@latest", want: true},
		{line: "deno run --strace-ops open,read npm:create-next-app@15.4.1", want: false},
		{line: "deno run --strace-filter=pid=1 npm:create-next-app@latest", want: true},
		{line: "deno run --strace-filter pid=1 npm:create-next-app@15.4.1", want: false},
		{line: "deno npm:create-vite@latest", want: true},
		{line: "deno npm:create-vite@5.2.0", want: false},
		{line: "deno", want: false},
		{line: "deno task start", want: false},
		{line: "echo deno run npm:create-vite", want: false},
		{line: "deno run --allow-read", want: false},
	}
	for _, tc := range cases {
		if got := isUnpinnedDenoNpmRuntimeLine(tc.line); got != tc.want {
			t.Fatalf("isUnpinnedDenoNpmRuntimeLine(%q) = %v, want %v", tc.line, got, tc.want)
		}
	}
}

func TestNextDenoRuntimeTarget(t *testing.T) {
	cases := []struct {
		name   string
		fields []string
		start  int
		end    int
		want   string
		ok     bool
	}{
		{
			name:   "reads npm specifier target",
			fields: []string{"deno", "run", "-A", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "skips split-value flags",
			fields: []string{"deno", "run", "--config", "deno.json", "--allow-read", "npm:cowsay"},
			start:  2,
			end:    6,
			want:   "npm:cowsay",
			ok:     true,
		},
		{
			name:   "reads token after separator",
			fields: []string{"deno", "run", "--allow-read", "--", "npm:cowsay"},
			start:  2,
			end:    5,
			want:   "npm:cowsay",
			ok:     true,
		},
		{
			name:   "returns false when no target",
			fields: []string{"deno", "run", "--allow-read"},
			start:  2,
			end:    3,
			want:   "",
			ok:     false,
		},
		{
			name:   "skips empty tokens",
			fields: []string{"deno", "run", "", "npm:cowsay"},
			start:  2,
			end:    4,
			want:   "npm:cowsay",
			ok:     true,
		},
		{
			name:   "skips equals-form flags",
			fields: []string{"deno", "run", "--config=deno.json", "npm:cowsay"},
			start:  2,
			end:    4,
			want:   "npm:cowsay",
			ok:     true,
		},
		{
			name:   "returns false when separator has no token",
			fields: []string{"deno", "run", "--allow-read", "--"},
			start:  2,
			end:    4,
			want:   "",
			ok:     false,
		},
		{
			name:   "clamps bounds and returns first token",
			fields: []string{"deno", "run", "npm:cowsay"},
			start:  -5,
			end:    99,
			want:   "deno",
			ok:     true,
		},
		{
			name:   "skips package flag and returns following target",
			fields: []string{"deno", "x", "--package", "npm:create-vite@5.2.0", "create-vite"},
			start:  2,
			end:    5,
			want:   "create-vite",
			ok:     true,
		},
		{
			name:   "skips package equals flag and returns following target",
			fields: []string{"deno", "x", "--package=npm:create-vite@5.2.0", "create-vite"},
			start:  2,
			end:    4,
			want:   "create-vite",
			ok:     true,
		},
		{
			name:   "skips generic split-value flag and returns target",
			fields: []string{"deno", "run", "--seed", "42", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "skips serve host split value and returns target",
			fields: []string{"deno", "serve", "--host", "127.0.0.1", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "skips serve port split value and returns target",
			fields: []string{"deno", "serve", "--port", "3000", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "skips install short-name split value and returns target",
			fields: []string{"deno", "install", "-n", "installer", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "skips install entrypoint split value and returns target",
			fields: []string{"deno", "install", "--entrypoint", "main.ts", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not treat reload as required-value flag",
			fields: []string{"deno", "run", "--reload", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not treat short reload as required-value flag",
			fields: []string{"deno", "run", "-r", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes reload blocklist value and returns following target",
			fields: []string{"deno", "run", "--reload", "npm:chalk@5", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes short reload blocklist value and returns following target",
			fields: []string{"deno", "run", "-r", "jsr:@std/http@1.0.0", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not treat vendor as required-value flag",
			fields: []string{"deno", "run", "--vendor", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes vendor optional bool value and returns following target",
			fields: []string{"deno", "run", "--vendor", "true", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not treat node-modules-dir as required-value flag",
			fields: []string{"deno", "run", "--node-modules-dir", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes node-modules-dir optional mode and returns following target",
			fields: []string{"deno", "run", "--node-modules-dir", "auto", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume install-alias when next token is runtime target",
			fields: []string{"deno", "x", "--install-alias", "npm:create-vite@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-vite@latest",
			ok:     true,
		},
		{
			name:   "consumes install-alias value and returns following target",
			fields: []string{"deno", "x", "--install-alias", "denox", "npm:create-vite@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-vite@latest",
			ok:     true,
		},
		{
			name:   "consumes node-modules-linker value and returns following target",
			fields: []string{"deno", "run", "--node-modules-linker", "isolated", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes minimum-dependency-age value and returns following target",
			fields: []string{"deno", "run", "--minimum-dependency-age", "0", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes tunnel value and returns following target",
			fields: []string{"deno", "run", "--tunnel", "preview", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes short tunnel value and returns following target",
			fields: []string{"deno", "run", "-t", "preview", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-scripts value and returns following target",
			fields: []string{"deno", "run", "--allow-scripts", "sqlite3", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume allow-scripts value when no following target exists",
			fields: []string{"deno", "run", "--allow-scripts", "sqlite3"},
			start:  2,
			end:    4,
			want:   "sqlite3",
			ok:     true,
		},
		{
			name:   "consumes allow-import value and returns following target",
			fields: []string{"deno", "run", "--allow-import", "deno.land", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes short allow-import value and returns following target",
			fields: []string{"deno", "run", "-I", "deno.land", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume allow-import value when no following target exists",
			fields: []string{"deno", "run", "--allow-import", "deno.land"},
			start:  2,
			end:    4,
			want:   "deno.land",
			ok:     true,
		},
		{
			name:   "consumes allow-read value and returns following target",
			fields: []string{"deno", "run", "--allow-read", ".", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-net value and returns following target",
			fields: []string{"deno", "run", "--allow-net", "deno.land", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-env value and returns following target",
			fields: []string{"deno", "run", "--allow-env", "PATH", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-write value and returns following target",
			fields: []string{"deno", "run", "--allow-write", ".", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-run value and returns following target",
			fields: []string{"deno", "run", "--allow-run", "deno", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-ffi value and returns following target",
			fields: []string{"deno", "run", "--allow-ffi", "./native.so", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes allow-sys value and returns following target",
			fields: []string{"deno", "run", "--allow-sys", "hostname", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes deny-read value and returns following target",
			fields: []string{"deno", "run", "--deny-read", ".", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes deny-net value and returns following target",
			fields: []string{"deno", "run", "--deny-net", "deno.land", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes deny-env value and returns following target",
			fields: []string{"deno", "run", "--deny-env", "PATH", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes inspect value and returns following target",
			fields: []string{"deno", "run", "--inspect", "127.0.0.1:9229", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes ext value and returns following target",
			fields: []string{"deno", "run", "--ext", "ts", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume env-file when next token is runtime target",
			fields: []string{"deno", "run", "--env-file", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume lock when next token is runtime target",
			fields: []string{"deno", "run", "--lock", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes lock value and returns following target",
			fields: []string{"deno", "run", "--lock", "deno.lock", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes cpu-prof-dir value and returns following target",
			fields: []string{"deno", "run", "--cpu-prof-dir", "profiles", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes cpu-prof-interval value and returns following target",
			fields: []string{"deno", "run", "--cpu-prof-interval", "1000", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes cpu-prof-name value and returns following target",
			fields: []string{"deno", "run", "--cpu-prof-name", "cpu.cpuprofile", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes env-file value and returns following target",
			fields: []string{"deno", "run", "--env-file", ".env", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes require value and returns following target",
			fields: []string{"deno", "run", "--require", "./loader.cjs", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes preload value and returns following target",
			fields: []string{"deno", "run", "--preload", "./preload.ts", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes import alias value and returns following target",
			fields: []string{"deno", "run", "--import", "./preload.ts", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes watch value and returns following target",
			fields: []string{"deno", "run", "--watch", "src", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes watch-exclude value and returns following target",
			fields: []string{"deno", "run", "--watch-exclude", "dist", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes watch-hmr value and returns following target",
			fields: []string{"deno", "run", "--watch-hmr", "src", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes conditions split value and returns following target",
			fields: []string{"deno", "run", "--conditions", "deno", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes coverage split value and returns following target",
			fields: []string{"deno", "run", "--coverage", "coverage", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume coverage when next token is runtime target",
			fields: []string{"deno", "run", "--coverage", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes v8-flags split value and returns following target",
			fields: []string{"deno", "run", "--v8-flags", "--harmony", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes no-check split value and returns following target",
			fields: []string{"deno", "run", "--no-check", "remote", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume no-check when next token is runtime target",
			fields: []string{"deno", "run", "--no-check", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes check split value and returns following target",
			fields: []string{"deno", "run", "--check", "all", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume check when next token is runtime target",
			fields: []string{"deno", "run", "--check", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes frozen split value and returns following target",
			fields: []string{"deno", "run", "--frozen", "false", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "does not consume frozen when next token is runtime target",
			fields: []string{"deno", "run", "--frozen", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes log-level split value and returns following target",
			fields: []string{"deno", "run", "--log-level", "debug", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes short log-level split value and returns following target",
			fields: []string{"deno", "run", "-L", "debug", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "treats unstable no-value flag as flag and returns following target",
			fields: []string{"deno", "run", "--unstable-kv", "npm:create-next-app@latest"},
			start:  2,
			end:    4,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes strace-ops split value and returns following target",
			fields: []string{"deno", "run", "--strace-ops", "open,read", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "consumes strace-filter split value and returns following target",
			fields: []string{"deno", "run", "--strace-filter", "pid=1", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   "npm:create-next-app@latest",
			ok:     true,
		},
		{
			name:   "returns false when start exceeds end",
			fields: []string{"deno", "run", "npm:cowsay"},
			start:  5,
			end:    3,
			want:   "",
			ok:     false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := nextDenoRuntimeTarget(tc.fields, tc.start, tc.end)
			if ok != tc.ok || got != tc.want {
				t.Fatalf("nextDenoRuntimeTarget(%v) = (%q, %v), want (%q, %v)", tc.fields, got, ok, tc.want, tc.ok)
			}
		})
	}

	t.Run("returns false for invalid bounds", func(t *testing.T) {
		fields := []string{"deno", "run", "npm:cowsay"}
		if got, ok := nextDenoRuntimeTarget(fields, -1, 0); ok || got != "" {
			t.Fatalf("nextDenoRuntimeTarget(%v, -1, 0) = (%q, %v), want (\"\", false)", fields, got, ok)
		}
	})
}

func TestHasDenoRuntimeCandidateAfter(t *testing.T) {
	cases := []struct {
		name   string
		fields []string
		start  int
		end    int
		want   bool
	}{
		{
			name:   "true when target exists after split value",
			fields: []string{"deno", "run", "--reload", "npm:chalk@5", "npm:create-next-app@latest"},
			start:  4,
			end:    5,
			want:   true,
		},
		{
			name:   "false when no following token",
			fields: []string{"deno", "run", "--reload", "npm:chalk@5"},
			start:  4,
			end:    4,
			want:   false,
		},
		{
			name:   "true when separator has explicit target",
			fields: []string{"deno", "run", "--allow-read", "--", "npm:cowsay"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "false when separator has no following target",
			fields: []string{"deno", "run", "--allow-read", "--"},
			start:  2,
			end:    4,
			want:   false,
		},
		{
			name:   "skips required-value flags and finds target",
			fields: []string{"deno", "run", "--config", "deno.json", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips require flag value and finds target",
			fields: []string{"deno", "run", "--require", "./loader.cjs", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips node-modules-linker value and finds target",
			fields: []string{"deno", "run", "--node-modules-linker", "isolated", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips minimum-dependency-age value and finds target",
			fields: []string{"deno", "run", "--minimum-dependency-age", "0", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips cpu-prof-dir value and finds target",
			fields: []string{"deno", "run", "--cpu-prof-dir", "profiles", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips cpu-prof-interval value and finds target",
			fields: []string{"deno", "run", "--cpu-prof-interval", "1000", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips cpu-prof-name value and finds target",
			fields: []string{"deno", "run", "--cpu-prof-name", "cpu.cpuprofile", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips tunnel value and finds target",
			fields: []string{"deno", "run", "--tunnel", "preview", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "finds target after install-alias split value",
			fields: []string{"deno", "x", "--install-alias", "denox", "npm:create-vite@latest"},
			start:  4,
			end:    5,
			want:   true,
		},
		{
			name:   "skips conditions split value and finds target",
			fields: []string{"deno", "run", "--conditions", "deno", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips host split value and finds target",
			fields: []string{"deno", "serve", "--host", "127.0.0.1", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips port split value and finds target",
			fields: []string{"deno", "serve", "--port", "3000", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips install short-name split value and finds target",
			fields: []string{"deno", "install", "-n", "installer", "main.ts"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "skips install entrypoint split value and finds target",
			fields: []string{"deno", "install", "--entrypoint", "main.ts", "npm:create-next-app@latest"},
			start:  2,
			end:    5,
			want:   true,
		},
		{
			name:   "returns false on invalid bounds",
			fields: []string{"deno", "run", "main.ts"},
			start:  5,
			end:    2,
			want:   false,
		},
		{
			name:   "clamps bounds and finds target",
			fields: []string{"deno", "run", "main.ts"},
			start:  -10,
			end:    99,
			want:   true,
		},
		{
			name:   "skips equals-form flags and finds target",
			fields: []string{"deno", "run", "--config=deno.json", "main.ts"},
			start:  2,
			end:    4,
			want:   true,
		},
		{
			name:   "skips empty tokens and finds target",
			fields: []string{"deno", "run", "", "main.ts"},
			start:  2,
			end:    4,
			want:   true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := hasDenoRuntimeCandidateAfter(tc.fields, tc.start, tc.end); got != tc.want {
				t.Fatalf("hasDenoRuntimeCandidateAfter(%v, %d, %d) = %v, want %v", tc.fields, tc.start, tc.end, got, tc.want)
			}
		})
	}
}
